project:
  name: "dist-sysgraph-web"
  environment: "prod"

angular:
  node_version: "25.5.0" # Angular 20/21 requer versões recentes do Node
  dir: "./app"

  # Lista dos MFEs que devem ser buildados e deployados
  apps:
  - dist-sysgraph-web
  # Adicione 'test' se for uma aplicação deployável, senão remova

terraform:
  version: "1.9.0"
  region: "us-east-1"

  # Configuração do bucket onde o site será hospedado
  bucket_config:
    name: "dist-sysgraph-web" # O nome deve ser globalmente único na AWS
    index_document: "index.html"
    error_document: "index.html"

  # Configuração do Backend remoto (Onde o tfstate será salvo)
  # Nota: O bucket de estado deve existir previamente ou você pode usar terraform cloud
  backend:
    bucket: "raysouz-terraform-state-repository"
    key: "dist-sysgraph-web/terraform.tfstate"
